In [1]:
import pandas as pd

In [2]:
meta_df = pd.read_json(
    "meta_Video_Games.jsonl",
    lines=True
)

In [3]:
meta_df.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Video Games,Dash 8-300 Professional Add-On,5.0,1,[Features Dash 8-300 and 8-Q300 ('Q' rollout l...,[The Dash 8-300 Professional Add-On lets you p...,None,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aerosoft,"[Video Games, PC, Games]",{'Pricing': 'The strikethrough price is the Li...,B000FH0MHO,NaN,NaN,NaN
1,Video Games,Phantasmagoria: A Puzzle of Flesh,4.1,18,[Windows 95],[],None,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sierra,"[Video Games, PC, Games]","{'Best Sellers Rank': {'Video Games': 137612, ...",B00069EVOG,NaN,NaN,NaN
2,Video Games,NBA 2K17 - Early Tip Off Edition - PlayStation 4,4.3,223,[The #1 rated NBA video game simulation series...,[Following the record-breaking launch of NBA 2...,58.0,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'NBA 2K17 - Kobe: Haters vs Players...,2K,"[Video Games, PlayStation 4, Games]","{'Release date': 'September 16, 2016', 'Best S...",B00Z9TLVK0,NaN,NaN,NaN
3,Video Games,Nintendo Selects: The Legend of Zelda Ocarina ...,4.9,22,[Authentic Nintendo Selects: The Legend of Zel...,[],37.42,[{'thumb': 'https://m.media-amazon.com/images/...,[],Amazon Renewed,"[Video Games, Legacy Systems, Nintendo Systems...","{'Best Sellers Rank': {'Video Games': 51019, '...",B07SZJZV88,NaN,NaN,NaN
4,Video Games,Thrustmaster Elite Fitness Pack for Nintendo Wii,3.0,3,"[Includes (9) Total Accessories, Pedometer, Wi...",[The Thrustmaster Motion Plus Elite Fitness Pa...,None,[{'thumb': 'https://m.media-amazon.com/images/...,[],THRUSTMASTER,"[Video Games, Legacy Systems, Nintendo Systems...","{'Release date': 'November 1, 2009', 'Pricing'...",B002WH4ZJG,NaN,NaN,NaN

In [4]:
meta_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137269 entries, 0 to 137268
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   main_category    126234 non-null  object
 1   title            137269 non-null  object
 2   average_rating   137269 non-null  float64
 3   rating_number    137269 non-null  int64
 4   features         137269 non-null  object
 5   description      137269 non-null  object
 6   price            62008 non-null   object
 7   images           137269 non-null  object
 8   videos           137269 non-null  object
 9   store            132908 non-null  object
 10  categories       137269 non-null  object
 11  details          137269 non-null  object
 12  parent_asin      137269 non-null  object
 13  bought_together  0 non-null       float64
 14  subtitle         350 non-null     object
 15  author           262 non-null     object
dtypes: float64(2), int64(1), object(13)
memory usage: 16.8+ MB

In [5]:
meta_df.shape

(137269, 16)

In [6]:
meta_df.columns

Index(['main_category', 'title', 'average_rating', 'rating_number', 'features',
       'description', 'price', 'images', 'videos', 'store', 'categories',
       'details', 'parent_asin', 'bought_together', 'subtitle', 'author'],
      dtype='object')

In [7]:
meta_df["main_category"].value_counts()

main_category
Video Games                     81255
Computers                       17235
All Electronics                 14816
Cell Phones & Accessories        3884
Toys & Games                     2733
Software                         1511
Industrial & Scientific          1079
Amazon Home                       737
Home Audio & Theater              443
Tools & Home Improvement          369
Office Products                   295
Sports & Outdoors                 244
Buy a Kindle                      220
Movies & TV                       197
Books                             196
Musical Instruments               154
All Beauty                        126
Camera & Photo                    117
Portable Audio & Accessories      112
Digital Music                     104
Health & Personal Care             95
Automotive                         85
AMAZON FASHION                     54
Pet Supplies                       38
Grocery                            36
Baby                               26
Arts, Crafts & Sewing              22
Car Electronics                    14
GPS & Navigation                   13
Appliances                         11
Amazon Devices                      4
Audible Audiobooks                  3
Collectible Coins                   3
Gift Cards                          1
Handmade                            1
                                    1
Name: count, dtype: int64

In [8]:
meta_df["categories"].head()

0                             [Video Games, PC, Games]
1                             [Video Games, PC, Games]
2                  [Video Games, PlayStation 4, Games]
3    [Video Games, Legacy Systems, Nintendo Systems...
4    [Video Games, Legacy Systems, Nintendo Systems...
Name: categories, dtype: object

In [9]:
video_games_df = meta_df[meta_df["main_category"] == "Video Games"].copy()

In [10]:
video_games_df.shape

(81255, 16)

In [11]:
video_games_df["Rating_Group"] = pd.cut(
    video_games_df["average_rating"],
    bins=[0, 2, 3, 4, 5],
    labels=["Poor", "Average", "Good", "Excellent"]
)

In [13]:
reviews_df = pd.read_json(
    "Video_Games.jsonl",
    lines=True
)

In [14]:
reviews_df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,It’s pretty sexual. Not my fav,I’m playing on ps5 and it’s interesting. It’s...,[],B07DJWBYKP,B07DK1H3H5,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-12-17 06:33:24.795,0,True
1,5,Good. A bit slow,Nostalgic fun. A bit slow. I hope they don’t...,[],B00ZS80PC2,B07SRWRH5D,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-04-16 15:31:54.941,1,False
2,5,... an order for my kids & they have really en...,This was an order for my kids & they have real...,[],B01FEHJYUU,B07MFMFW34,AGXVBIUFLFGMVLATYXHJYL4A5Q7Q,2017-03-30 12:37:11.000,0,True
3,5,Great alt to pro controller,"These work great, They use batteries which is ...",[],B07GXJHRVK,B0BCHWZX95,AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q,2019-12-29 16:40:34.017,0,True
4,5,solid product,I would recommend to anyone looking to add jus...,[],B00HUWA45W,B00HUWA45W,AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q,2015-03-29 01:18:52.000,0,True

In [15]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624615 entries, 0 to 4624614
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   rating             int64
 1   title              object
 2   text               object
 3   images             object
 4   asin               object
 5   parent_asin        object
 6   user_id            object
 7   timestamp          datetime64[ns]
 8   helpful_vote       int64
 9   verified_purchase  bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(6)
memory usage: 322.0+ MB

In [16]:
reviews_df.shape

(4624615, 10)

In [17]:
reviews_df.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase'],
      dtype='object')

In [19]:
merged_df = meta_df.merge(
    reviews_df,
    on="parent_asin",
    how="inner"
)

In [20]:
print("Rows :", merged_df.shape[0])
print("Columns :", merged_df.shape[1])

Rows : 4624615
Columns : 25

In [21]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624615 entries, 0 to 4624614
Data columns (total 25 columns):
 #   Column             Dtype
---  ------             -----
 0   main_category      object
 1   title_x            object
 2   average_rating     float64
 3   rating_number      int64
 4   features           object
 5   description        object
 6   price              object
 7   images_x           object
 8   videos             object
 9   store              object
 10  categories         object
 11  details            object
 12  parent_asin        object
 13  bought_together    float64
 14  subtitle           object
 15  author             object
 16  rating             int64
 17  title_y            object
 18  text               object
 19  images_y           object
 20  asin               object
 21  user_id            object
 22  timestamp          datetime64[ns]
 23  helpful_vote       int64
 24  verified_purchase  bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(3), object(18)
memory usage: 851.2+ MB

In [22]:
missing = (
    merged_df.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

bought_together    4624615
subtitle           4613235
author             4607506
price              1396611
main_category        79766
store                19391
dtype: int64

In [24]:
merged_df.dtypes

main_category                object
title_x                      object
average_rating              float64
rating_number                 int64
features                     object
description                  object
price                        object
images_x                     object
videos                       object
store                        object
categories                   object
details                      object
parent_asin                  object
bought_together             float64
subtitle                     object
author                       object
rating                        int64
title_y                      object
text                         object
images_y                     object
asin                         object
user_id                      object
timestamp            datetime64[ns]
helpful_vote                  int64
verified_purchase              bool
dtype: object

In [25]:
for col in merged_df.columns:
    if merged_df[col].dtype == "object":
        first = merged_df[col].dropna()
        if len(first) > 0:
            print(col, type(first.iloc[0]))

main_category <class 'str'>
title_x <class 'str'>
features <class 'list'>
description <class 'list'>
price <class 'float'>
images_x <class 'list'>
videos <class 'list'>
store <class 'str'>
categories <class 'list'>
details <class 'dict'>
parent_asin <class 'str'>
subtitle <class 'str'>
author <class 'dict'>
title_y <class 'str'>
text <class 'str'>
images_y <class 'list'>
asin <class 'str'>
user_id <class 'str'>

In [26]:
print(
    "Duplicate Reviews:",
    merged_df.duplicated(
        subset=[
            "user_id",
            "parent_asin",
            "timestamp"
        ]
    ).sum()
)

Duplicate Reviews: 53653

In [27]:
print(
    "Duplicate Reviews:",
    merged_df.duplicated(
        subset=[
            "user_id",
            "parent_asin",
            "text"
        ]
    ).sum()
)

Duplicate Reviews: 57836

In [28]:
print(
    "Duplicate Products:",
    merged_df.duplicated(
        subset=["parent_asin"]
    ).sum()
)

Duplicate Products: 4487366

In [29]:
print(
    "Duplicate Metadata:",
    merged_df.duplicated(
        subset=[
            "parent_asin",
            "title_x"
        ]
    ).sum()
)

Duplicate Metadata: 4487366

In [30]:
print(
    "Duplicate Reviews:",
    merged_df.duplicated(
        subset=["user_id", "parent_asin", "timestamp"]
    ).sum()
)

Duplicate Reviews: 53653

In [ ]:
merged_df.describe(include="all")